package com.dgb.dosha.domain.notification;

public enum NotiType {
	MANAGER_APPOINTMENTS,
	MANAGER_EDUCATIONS,
	SUBMANAGER_APPOINTMENTS,
	INSPECTION_REQUIRED,
	INSPECTION_CHECKED,
	PROCEEDINGS_CHECKED,
	RISK_CHECKED,
}
